# Generated by Django 6.0.5 on 2026-05-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comment_options_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
    ]
